### ISSUE TITLE
verify_build --template option has no effect

### ISSUE THREAD

**Issue by gregoire-mullvad** [transparency-dev/armored-witness#212]
I'm playing around with verify_build, and I noticed that passing `--template=ci` has no effect and I suspect it's because the code is trying to access the value of the template option before the flags are parsed (I think they they are parsed in cobra.Command.Execute).

I think it might be easy to fix using cobra hooks, I can try to make a PR if you want.

**Comment by AlCutter** [comment]
Hi @gregoire-mullvad - nice catch, a PR would be very welcome - thank you!
